##
# Fixed by Mike <mike@pavilion-health.com> was breaking Windows build on GoCD
# Please do not overwrite or regenerate this file
#
# NO || Generated by jeweler
# NO || DO NOT EDIT THIS FILE
# NO || Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# NO || -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'ruby-hl7'
  s.version = '1.0.5'
  s.authors = ['Mark Guzman', 'Mike Pollitt']
  s.date = '2017-09-04'
  s.description = 'A simple library to parse and generate HL7 2.x messages'
  s.email = 'ruby-hl7@googlegroups.com'
  s.licenses      = ['MIT']
  s.files         = [
    "Rakefile",
    "examples/proxy_server.rb",
    "lib/core_ext/date_time.rb",
    "lib/core_ext/string.rb",
    "lib/data_types.rb",
    "lib/message.rb",
    "lib/message_parser.rb",
    "lib/ruby-hl7.rb",
    "lib/segment.rb",
    "lib/segment_default.rb",
    "lib/segment_fields.rb",
    "lib/segment_generator.rb",
    "lib/segment_list_storage.rb",
    "lib/segments/abs.rb",
    "lib/segments/al1.rb",
    "lib/segments/dg1.rb",
    "lib/segments/drg.rb",
    "lib/segments/err.rb",
    "lib/segments/evn.rb",
    "lib/segments/in1.rb",
    "lib/segments/mrg.rb",
    "lib/segments/msa.rb",
    "lib/segments/msh.rb",
    "lib/segments/nk1.rb",
    "lib/segments/nte.rb",
    "lib/segments/obr.rb",
    "lib/segments/obx.rb",
    "lib/segments/orc.rb",
    "lib/segments/oru.rb",
    "lib/segments/pid.rb",
    "lib/segments/pr1.rb",
    "lib/segments/pra.rb",
    "lib/segments/pv1.rb",
    "lib/segments/pv2.rb",
    "lib/segments/qrd.rb",
    "lib/segments/qrf.rb",
    "lib/segments/rxc.rb",
    "lib/segments/rxe.rb",
    "lib/segments/rxr.rb",
    "lib/segments/sft.rb",
    "lib/segments/spm.rb",
    "lib/segments/stf.rb",
    "lib/segments/zcf.rb",
    "lib/segments/zed.rb",
    "lib/segments/zp1.rb",
    "lib/test/hl7_messages.rb",
  ]
  s.test_files    = Dir.glob("{spec,test}/**/*.rb")
  s.homepage = 'https://github.com/ruby-hl7/ruby-hl7'
  s.require_paths = ['lib']
  s.summary = 'Ruby HL7 Library'
end
