##
# Fixed by Mike <mike@pavilion-health.com> was breaking Windows build on GoCD
# Please do not overwrite or regenerate this file
#
# NO || Generated by jeweler
# NO || DO NOT EDIT THIS FILE
# NO || Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# NO || -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = 'ruby-hl7'
  s.version = '1.0.4'

  # s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ['Mark Guzman', 'Mike Pollitt']
  s.date = '2017-09-04'
  s.description = 'A simple library to parse and generate HL7 2.x messages'
  s.email = 'ruby-hl7@googlegroups.com'
  s.extra_rdoc_files = [
    "LICENSE",
    "README.md"
  ]
  s.licenses      = ['MIT']
  s.files         = [
    ".gitignore",
    ".travis.yml",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "NOTES.md",
    "README.md",
    "Rakefile",
    "VERSION",
    "VERSION.yml",
    "examples/proxy_server.rb",
    "lib/core_ext/date_time.rb",
    "lib/core_ext/string.rb",
    "lib/data_types.rb",
    "lib/message.rb",
    "lib/message_parser.rb",
    "lib/ruby-hl7.rb",
    "lib/segment.rb",
    "lib/segment_default.rb",
    "lib/segment_fields.rb",
    "lib/segment_generator.rb",
    "lib/segment_list_storage.rb",
    "lib/segments/abs.rb",
    "lib/segments/al1.rb",
    "lib/segments/dg1.rb",
    "lib/segments/drg.rb",
    "lib/segments/err.rb",
    "lib/segments/evn.rb",
    "lib/segments/in1.rb",
    "lib/segments/mrg.rb",
    "lib/segments/msa.rb",
    "lib/segments/msh.rb",
    "lib/segments/nk1.rb",
    "lib/segments/nte.rb",
    "lib/segments/obr.rb",
    "lib/segments/obx.rb",
    "lib/segments/orc.rb",
    "lib/segments/oru.rb",
    "lib/segments/pid.rb",
    "lib/segments/pr1.rb",
    "lib/segments/pra.rb",
    "lib/segments/pv1.rb",
    "lib/segments/pv2.rb",
    "lib/segments/qrd.rb",
    "lib/segments/qrf.rb",
    "lib/segments/rxc.rb",
    "lib/segments/rxe.rb",
    "lib/segments/rxr.rb",
    "lib/segments/sft.rb",
    "lib/segments/spm.rb",
    "lib/segments/stf.rb",
    "lib/segments/zcf.rb",
    "lib/segments/zed.rb",
    "lib/segments/zp1.rb",
    "lib/test/hl7_messages.rb",
    "ruby-hl7.gemspec",
    "spec/basic_parsing_spec.rb",
    "spec/batch_parsing_spec.rb",
    "spec/child_segment_spec.rb",
    "spec/core_ext/date_time_spec.rb",
    "spec/default_segment_spec.rb",
    "spec/dynamic_segment_def_spec.rb",
    "spec/err_segment_spec.rb",
    "spec/msa_segment_spec.rb",
    "spec/msh_segment_spec.rb",
    "spec/nk1_segment_spec.rb",
    "spec/obr_segment_spec.rb",
    "spec/obx_segment_spec.rb",
    "spec/orc_segment_spec.rb",
    "spec/pid_segment_spec.rb",
    "spec/pv1_segment_spec.rb",
    "spec/segment_field_spec.rb",
    "spec/segment_generator_spec.rb",
    "spec/segment_list_storage_spec.rb",
    "spec/segment_spec.rb",
    "spec/sft_segment_spec.rb",
    "spec/spec_helper.rb",
    "spec/speed_parsing_spec.rb",
    "spec/spm_segment_spec.rb",
    "test_data/adt_a01.hl7",
    "test_data/cerner/cerner_bordetella.hl7",
    "test_data/cerner/cerner_en.hl7",
    "test_data/cerner/cerner_lead.hl7",
    "test_data/cerner/cerner_sequential.hl7",
    "test_data/empty-batch.hl7",
    "test_data/empty.hl7",
    "test_data/empty_segments.hl7",
    "test_data/lotsunknowns.hl7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase1.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase2.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase3.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase4.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase5.er7",
    "test_data/nist/ORU_R01_2.5.1_SampleTestCase6.er7",
    "test_data/obxobr.hl7",
    "test_data/pid_name.hl7",
    "test_data/realm/realm-animal-rabies.hl7",
    "test_data/realm/realm-bad-batch.hl7",
    "test_data/realm/realm-batch.hl7",
    "test_data/realm/realm-campylobacter-jejuni.hl7",
    "test_data/realm/realm-cj-badloinc.hl7",
    "test_data/realm/realm-cj-joeslab.hl7",
    "test_data/realm/realm-cj.hl7",
    "test_data/realm/realm-err.hl7",
    "test_data/realm/realm-hepatitis-c-virus.hl7",
    "test_data/realm/realm-lead-laboratory-result.hl7",
    "test_data/realm/realm-minimal-message.hl7",
    "test_data/rqi_r04.hl7",
    "test_data/test.hl7",
    "test_data/test2.hl7",
    "test_data/zed.hl7"
  ]
  s.test_files    = [
    "spec/basic_parsing_spec.rb",
    "spec/batch_parsing_spec.rb",
    "spec/child_segment_spec.rb",
    "spec/core_ext/date_time_spec.rb",
    "spec/default_segment_spec.rb",
    "spec/dynamic_segment_def_spec.rb",
    "spec/err_segment_spec.rb",
    "spec/msa_segment_spec.rb",
    "spec/msh_segment_spec.rb",
    "spec/nk1_segment_spec.rb",
    "spec/obr_segment_spec.rb",
    "spec/obx_segment_spec.rb",
    "spec/orc_segment_spec.rb",
    "spec/pid_segment_spec.rb",
    "spec/pv1_segment_spec.rb",
    "spec/segment_field_spec.rb",
    "spec/segment_generator_spec.rb",
    "spec/segment_list_storage_spec.rb",
    "spec/segment_spec.rb",
    "spec/sft_segment_spec.rb",
    "spec/spec_helper.rb",
    "spec/speed_parsing_spec.rb",
    "spec/spm_segment_spec.rb"
  ]
  s.homepage = 'https://github.com/ruby-hl7/ruby-hl7'
  s.rdoc_options = ['--charset=UTF-8']
  s.require_paths = ['lib']
  s.required_ruby_version = Gem::Requirement.new('>= 1.8.6')
  s.rubyforge_project = 'ruby-hl7'
  s.rubygems_version = '1.4.2'
  s.summary = 'Ruby HL7 Library'

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency 'rake', '~> 10.0', '>= 10.0.0'
      s.add_runtime_dependency 'rubyforge', '~> 2.0', '>= 2.0.4'
    else
      s.add_dependency('rake', ['>= 10.0.0'])
      s.add_dependency('rubyforge', ['>= 2.0.4'])
    end
  else
    s.add_dependency('rake', ['>= 10.0.0'])
    s.add_dependency('rubyforge', ['>= 2.0.4'])
  end
end
